name: mise à jour des données

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create data.json
        run: |
          mkdir -p fichiers
          echo '{
            "images": [],
            "videos": {},
            "files": {}
          }' > fichiers/data.json
          
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fichiers/data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data.json"
          git push
